import { Email } from "../data/mockData";
import { Download } from "lucide-react";

export function TranscriptDownloader({ email, currentUser = { name: "Ripun", email: "hello@theripun.com" } }: { email: Email, currentUser?: { name: string, email: string } }) {
  const handleDownload = () => {
    // Create an invisible iframe
    const iframe = document.createElement('iframe');
    iframe.style.position = 'absolute';
    iframe.style.width = '0';
    iframe.style.height = '0';
    iframe.style.border = 'none';
    document.body.appendChild(iframe);

    const allMessages = email.thread || [];
    const initialMessage = {
      id: email.id,
      senderName: email.senderName,
      senderEmail: email.senderEmail,
      date: email.date,
      body: email.body,
    };

    const threadToPrint = [initialMessage, ...allMessages];

    // Build the HTML content
    const htmlContent = `
      <!DOCTYPE html>
      <html>
        <head>
          <title>Transcript - ${email.subject}</title>
          <style>
            body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; color: #000; line-height: 1.6; padding: 20px; }
            .header { display: flex; justify-content: space-between; border-bottom: 2px solid #eee; padding-bottom: 20px; margin-bottom: 30px; }
            .logo { max-width: 120px; filter: invert(1); } /* Invert logo to black */
            .meta { text-align: right; color: #555; font-size: 12px; }
            .meta h2 { color: #000; font-size: 18px; margin: 0 0 5px 0; }
            .meta p { margin: 2px 0; }
            .subject-area { margin-bottom: 40px; }
            .subject-area h1 { font-size: 24px; margin: 0 0 5px 0; }
            .subject-area p { color: #555; font-size: 14px; margin: 0; }
            .message { border: 1px solid #ddd; border-radius: 8px; padding: 20px; margin-bottom: 20px; background: #fafafa; page-break-inside: avoid; }
            .msg-header { display: flex; justify-content: space-between; border-bottom: 1px solid #eee; padding-bottom: 10px; margin-bottom: 15px; }
            .msg-header .sender { font-weight: bold; }
            .msg-header .email { color: #666; font-size: 14px; }
            .msg-header .date { color: #555; font-size: 14px; }
            .msg-body { font-size: 14px; }
            .msg-body blockquote { border-left: 3px solid #ccc; margin: 0; padding-left: 10px; color: #555; }
            .footer { margin-top: 50px; border-top: 1px solid #eee; padding-top: 20px; text-align: center; color: #999; font-size: 11px; }
            @media print {
              body { padding: 0; }
            }
          </style>
        </head>
        <body>
          <div class="header">
            <div>
              <!-- We use the absolute URL to ensure it loads in the iframe -->
              <img src="${window.location.origin}/logo/logo-01.png" class="logo" alt="Norest Logo" />
            </div>
            <div class="meta">
              <h2>Email Transcript</h2>
              <p>Generated by ${currentUser.name}</p>
              <p>${currentUser.email}</p>
              <p>${new Date().toLocaleString()}</p>
            </div>
          </div>
          <div class="subject-area">
            <h1>${email.subject}</h1>
            <p>Total messages: ${threadToPrint.length}</p>
          </div>
          <div class="messages">
            ${threadToPrint.map(msg => `
              <div class="message">
                <div class="msg-header">
                  <div>
                    <span class="sender">${msg.senderName}</span> <span class="email">&lt;${msg.senderEmail}&gt;</span>
                  </div>
                  <div class="date">${msg.date}</div>
                </div>
                <div class="msg-body">${msg.body}</div>
              </div>
            `).join('')}
          </div>
          <div class="footer">
            Document generated by Norest Mail.
          </div>
          <script>
            // Wait for images to load before printing
            window.onload = function() {
              window.print();
              // Clean up the iframe after print dialogue closes
              setTimeout(function() {
                window.parent.document.body.removeChild(window.frameElement);
              }, 1000);
            };
          </script>
        </body>
      </html>
    `;

    const doc = iframe.contentWindow?.document;
    if (doc) {
      doc.open();
      doc.write(htmlContent);
      doc.close();
    }
  };

  return (
    <button
      onClick={handleDownload}
      className="h-8 px-3 cursor-pointer rounded-full bg-white dark:bg-black/5 border border-border-divider flex items-center gap-2 hover:bg-black/5 dark:hover:bg-white/5 transition-colors text-text-secondary hover:text-text-primary"
      title="Print or Save as PDF"
    >
      <Download size={14} />
      <span className="text-[12px] font-semibold hidden sm:block">Download PDF</span>
    </button>
  );
}
